/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import { Feature } from '@/components/Feature';
import { features } from '@/data/features';
import Link from 'next/link';
import renderSkin from '@/assets/images/renderSkin.png';
import { useMediaQuery } from '@material-ui/core';

export default function Home() {
  const onClickDetails = () => {
    window.scrollTo({ left: 0, top: 1000, behavior: 'smooth' });
  };

  const onClickNext = () => {
    window.scrollTo({ left: 0, top: document.body.scrollHeight, behavior: 'smooth' });
  };

  const matches1500 = useMediaQuery('(max-width:1500px)');

  return (
    <>
      <Head>
        <title>UpCraft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.mainPageBlock}>
          <div className={styles.welcomeTextBlock}>
            <span className={styles.welcomeTextBlockHead}>UpCraft</span>
            <span className={styles.welcomeTextBlockText}>Открой для себя новый мир</span>
          </div>
          {!matches1500 && (
            <div className={styles.toDetailsBlock} onClick={onClickDetails}>
              <svg
                width="49"
                height="49"
                viewBox="0 0 49 49"
                fill="none"
                xmlns="http://www.w3.org/2000/svg">
                <g clipPath="url(#clip0_15_5)">
                  <path
                    d="M24.5 33.2588C24.8267 33.2588 25.1329 33.2073 25.4188 33.1044C25.7046 33.0031 25.97 32.83 26.215 32.585L32.585 26.215C33.0342 25.7658 33.2588 25.1942 33.2588 24.5C33.2588 23.8058 33.0342 23.2342 32.585 22.785C32.1358 22.3358 31.5642 22.1112 30.87 22.1112C30.1758 22.1112 29.6042 22.3358 29.155 22.785L26.95 24.99V17.15C26.95 16.4558 26.7156 15.8735 26.2469 15.4031C25.7765 14.9344 25.1942 14.7 24.5 14.7C23.8058 14.7 23.2244 14.9344 22.7556 15.4031C22.2852 15.8735 22.05 16.4558 22.05 17.15V24.99L19.845 22.785C19.3958 22.3358 18.8242 22.1112 18.13 22.1112C17.4358 22.1112 16.8642 22.3358 16.415 22.785C15.9658 23.2342 15.7413 23.8058 15.7413 24.5C15.7413 25.1942 15.9658 25.7658 16.415 26.215L22.785 32.585C23.03 32.83 23.2954 33.0031 23.5813 33.1044C23.8671 33.2073 24.1733 33.2588 24.5 33.2588ZM24.5 49C21.1108 49 17.9258 48.3565 14.945 47.0694C11.9642 45.784 9.37125 44.0388 7.16625 41.8338C4.96125 39.6288 3.21603 37.0358 1.9306 34.055C0.643534 31.0742 0 27.8892 0 24.5C0 21.1108 0.643534 17.9258 1.9306 14.945C3.21603 11.9642 4.96125 9.37125 7.16625 7.16625C9.37125 4.96125 11.9642 3.21522 14.945 1.92815C17.9258 0.642717 21.1108 0 24.5 0C27.8892 0 31.0742 0.642717 34.055 1.92815C37.0358 3.21522 39.6288 4.96125 41.8338 7.16625C44.0388 9.37125 45.784 11.9642 47.0694 14.945C48.3565 17.9258 49 21.1108 49 24.5C49 27.8892 48.3565 31.0742 47.0694 34.055C45.784 37.0358 44.0388 39.6288 41.8338 41.8338C39.6288 44.0388 37.0358 45.784 34.055 47.0694C31.0742 48.3565 27.8892 49 24.5 49Z"
                    fill="white"
                  />
                </g>
                <defs>
                  <clipPath id="clip0_15_5">
                    <rect width="49" height="49" fill="white" />
                  </clipPath>
                </defs>
              </svg>
              <span className={styles.moreDetailsText}>Подробнее</span>
            </div>
          )}
        </div>
        <div className={`${styles.aboutProject} ${styles.container}`}>
          <div className={styles.aboutProjectWrapper}>
            <div>
              <h2>Что такое UpCraft?</h2>
              <p>
                UpCraft - это проект с модами популярной игры <span>Minecraft</span>.
              </p>
              <p>
                У нас есть 4 сервера с разными сборками модов, которые подойдут по вкусу
                <span> каждому</span>. На этих серверах присутствует несколько наших
                <span> самописных модификаций</span>.
              </p>
              <p>
                На каждом сервере присутствует <span>особая концепция</span> игры - прокачка
                персонажа и поэтапное открытие крафтов.
              </p>
              <p>
                Каждый новичок начинает игру с <span>первого</span> уровня, имея при себе несколько
                предметов в инвентаре. Вам предстоит дойти до последнего - <span>сотого </span>
                уровня.
              </p>
            </div>
            <img
              className={styles.aboutUsBackgroundImage}
              src={renderSkin.src}
              alt="backgroundImage"
              width={524}
              height={637}
            />
          </div>
          {!matches1500 && (
            <button className={styles.nextStepButton} onClick={onClickNext}>
              <span>ДАЛЕЕ</span>
              <svg
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
                xmlns="http://www.w3.org/2000/svg">
                <g clipPath="url(#clip0_51_2971)">
                  <path
                    d="M10.7 13.3L13.3 10.7C13.4833 10.5167 13.575 10.2833 13.575 10C13.575 9.71667 13.4833 9.48333 13.3 9.3L10.675 6.675C10.4917 6.49167 10.2627 6.404 9.988 6.412C9.71267 6.42067 9.48333 6.51667 9.3 6.7C9.11667 6.88333 9.025 7.11667 9.025 7.4C9.025 7.68333 9.11667 7.91667 9.3 8.1L10.2 9H6.975C6.69167 9 6.45833 9.09567 6.275 9.287C6.09167 9.479 6 9.71667 6 10C6 10.2833 6.096 10.5207 6.288 10.712C6.47933 10.904 6.71667 11 7 11H10.2L9.275 11.925C9.09167 12.1083 9.004 12.3377 9.012 12.613C9.02067 12.8877 9.11667 13.1167 9.3 13.3C9.48333 13.4833 9.71667 13.575 10 13.575C10.2833 13.575 10.5167 13.4833 10.7 13.3ZM10 20C8.61667 20 7.31667 19.7373 6.1 19.212C4.88333 18.6873 3.825 17.975 2.925 17.075C2.025 16.175 1.31267 15.1167 0.788 13.9C0.262667 12.6833 0 11.3833 0 10C0 8.61667 0.262667 7.31667 0.788 6.1C1.31267 4.88333 2.025 3.825 2.925 2.925C3.825 2.025 4.88333 1.31233 6.1 0.787C7.31667 0.262333 8.61667 0 10 0C11.3833 0 12.6833 0.262333 13.9 0.787C15.1167 1.31233 16.175 2.025 17.075 2.925C17.975 3.825 18.6873 4.88333 19.212 6.1C19.7373 7.31667 20 8.61667 20 10C20 11.3833 19.7373 12.6833 19.212 13.9C18.6873 15.1167 17.975 16.175 17.075 17.075C16.175 17.975 15.1167 18.6873 13.9 19.212C12.6833 19.7373 11.3833 20 10 20Z"
                    fill="white"
                  />
                </g>
                <defs>
                  <clipPath id="clip0_51_2971">
                    <rect width="20" height="20" fill="white" />
                  </clipPath>
                </defs>
              </svg>
            </button>
          )}
        </div>
        <hr className={styles.line} />
        <div className={`${styles.featuresBlock} ${styles.container}`}>
          <h2>Почему именно мы?</h2>
          <div className={styles.features}>
            {features.map((obj) => (
              <Feature {...obj} key={obj.text} />
            ))}
          </div>
          <Link href={'/start'}>
            <button
              className={styles.nextStepButton}
              style={{
                marginTop: 150,
                marginBottom: 50,
              }}>
              <span>ДАЛЕЕ</span>
              <svg
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
                xmlns="http://www.w3.org/2000/svg">
                <g clipPath="url(#clip0_51_2971)">
                  <path
                    d="M10.7 13.3L13.3 10.7C13.4833 10.5167 13.575 10.2833 13.575 10C13.575 9.71667 13.4833 9.48333 13.3 9.3L10.675 6.675C10.4917 6.49167 10.2627 6.404 9.988 6.412C9.71267 6.42067 9.48333 6.51667 9.3 6.7C9.11667 6.88333 9.025 7.11667 9.025 7.4C9.025 7.68333 9.11667 7.91667 9.3 8.1L10.2 9H6.975C6.69167 9 6.45833 9.09567 6.275 9.287C6.09167 9.479 6 9.71667 6 10C6 10.2833 6.096 10.5207 6.288 10.712C6.47933 10.904 6.71667 11 7 11H10.2L9.275 11.925C9.09167 12.1083 9.004 12.3377 9.012 12.613C9.02067 12.8877 9.11667 13.1167 9.3 13.3C9.48333 13.4833 9.71667 13.575 10 13.575C10.2833 13.575 10.5167 13.4833 10.7 13.3ZM10 20C8.61667 20 7.31667 19.7373 6.1 19.212C4.88333 18.6873 3.825 17.975 2.925 17.075C2.025 16.175 1.31267 15.1167 0.788 13.9C0.262667 12.6833 0 11.3833 0 10C0 8.61667 0.262667 7.31667 0.788 6.1C1.31267 4.88333 2.025 3.825 2.925 2.925C3.825 2.025 4.88333 1.31233 6.1 0.787C7.31667 0.262333 8.61667 0 10 0C11.3833 0 12.6833 0.262333 13.9 0.787C15.1167 1.31233 16.175 2.025 17.075 2.925C17.975 3.825 18.6873 4.88333 19.212 6.1C19.7373 7.31667 20 8.61667 20 10C20 11.3833 19.7373 12.6833 19.212 13.9C18.6873 15.1167 17.975 16.175 17.075 17.075C16.175 17.975 15.1167 18.6873 13.9 19.212C12.6833 19.7373 11.3833 20 10 20Z"
                    fill="white"
                  />
                </g>
                <defs>
                  <clipPath id="clip0_51_2971">
                    <rect width="20" height="20" fill="white" />
                  </clipPath>
                </defs>
              </svg>
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
